# Generated by Django 2.2.7 on 2019-11-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('type', models.IntegerField(max_length=10)),
                ('is_deleted', models.IntegerField(max_length=10)),
                ('modified_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
