# Generated by Django 2.2.7 on 2019-11-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_location', models.CharField(max_length=50, verbose_name='圆心的经纬度')),
                ('radius', models.IntegerField(verbose_name='圆的半径')),
                ('modified_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='修改时间')),
                ('created_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Keymsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='api的请求key')),
                ('type', models.IntegerField(default=0, verbose_name='key的类型，0：高德地图')),
                ('is_deleted', models.IntegerField(default=0, verbose_name='是否已删除，0：未删除，1：已删除')),
                ('modified_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='修改时间')),
                ('created_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='交通名称')),
                ('location', models.CharField(max_length=50, verbose_name='交通经纬度')),
                ('modified_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='修改时间')),
                ('created_time', models.DateTimeField(default='2019-11-24 22:12:47', verbose_name='创建时间')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Circle')),
            ],
        ),
        migrations.CreateModel(
            name='Transit_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_per_cost', models.FloatField(max_length=10, verbose_name='总平均费用（元）')),
                ('total_per_duration', models.FloatField(max_length=10, verbose_name='总平均时间（秒）')),
                ('total_per_walking_distance', models.FloatField(max_length=10, verbose_name='总平均步行路程（米）')),
                ('total_per_distance', models.FloatField(max_length=10, verbose_name='总平均距离（米）')),
                ('detail', models.TextField(verbose_name='路程详细信息')),
                ('around_market', models.TextField(verbose_name='周边超市')),
                ('around_housing', models.TextField(verbose_name='周边公寓')),
                ('traffic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Traffic_info')),
            ],
        ),
    ]
