# Generated by Django 2.2.7 on 2019-11-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_msg',
            new_name='Keymsg',
        ),
    ]
