# Generated by Django 2.2.7 on 2019-11-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit_detail',
            name='circle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.Circle'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='created_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='modified_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='created_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='modified_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='created_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='modified_time',
            field=models.DateTimeField(default='2019-11-25 21:29:49', verbose_name='修改时间'),
        ),
    ]
