# Generated by Django 2.2.7 on 2019-12-03 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20191125_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='created_time',
            field=models.DateTimeField(default='2019-12-03 20:57:06', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='modified_time',
            field=models.DateTimeField(default='2019-12-03 20:57:06', verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 12, 57, 6, 637843, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 12, 57, 6, 637843, tzinfo=utc), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='created_time',
            field=models.DateTimeField(default='2019-12-03 20:57:06', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='modified_time',
            field=models.DateTimeField(default='2019-12-03 20:57:06', verbose_name='修改时间'),
        ),
    ]
