# Generated by Django 2.2.7 on 2019-11-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20191109_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymsg',
            name='created_time',
            field=models.DateTimeField(default='2019-11-09 14:43:53'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='is_deleted',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='modified_time',
            field=models.DateTimeField(default='2019-11-09 14:43:53'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='type',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
