# Generated by Django 3.0.7 on 2020-06-07 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20191203_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 160411, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 160381, tzinfo=utc), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 159755, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='keymsg',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 159701, tzinfo=utc), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 160952, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='traffic_info',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 160923, tzinfo=utc), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='transit_detail',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 161625, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='transit_detail',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 4, 56, 0, 161598, tzinfo=utc), verbose_name='修改时间'),
        ),
    ]
